const date = new Date();
const year = date.getFullYear();

export const SITE_DATA = {
    name: "Typetools",
    author: {
        name: "Unforma™Club",
        url: "https://unforma.club",
    },
    years: ["2020", year],
};

export const DUMMY_TEXT = `Die Columbia, der erste raumflugfähige Orbiter, wurde im März 1979 an die NASA ausgeliefert. Anschließend wurde die Raumfähre ins Kennedy Space Center überführt, um dort auf ihre erste Mission vorbereitet zu werden. Im November 1980 wurde die Columbia mit dem Außentank verbunden und einen Monat später zur Startrampe gefahren. Nach mehreren Startverschiebungen fand am 12. April 1981 der Start des ersten wiederverwendbaren Raumfahrzeuges der Welt statt. Ziel des ersten Fluges war es lediglich, die Columbia sicher in die Umlaufbahn und wieder zurück zu bringen. Der Flug dauerte insgesamt etwas über zwei Tage und endete mit einer Landung auf der Edwards Air Force Base in Kalifornien. Der Erstflug gilt bis heute als technische Meisterleistung, denn es war das erste Mal in der Geschichte der Raumfahrt, dass ein Trägersystem bei seinem Jungfernflug bemannt war. Die folgenden drei Flüge, die alle mit der Raumfähre Columbia durchgeführt wurden, dienten der Erprobung aller Systeme des Shuttle. Danach wurde das System als einsatzfähig erklärt. In den darauf folgenden 21 Missionen, die bis Januar 1986 durchgeführt wurden, stand der Satellitentransport im Vordergrund. Außerdem fanden einige rein wissenschaftliche Flüge statt, bevor es zum Challenger-Unglück kam. Am 28. Januar 1986 hob die Raumfähre Challenger bei einer ungewöhnlich niedrigen Außentemperatur von 2 °C zur Mission STS-51-L ab. Die NASA hatte sich für den Start entschieden, obwohl Ingenieure des Booster-Herstellers Morton Thiokol, vor allem Roger Boisjoly, vor einem Start bei Temperaturen unter 12 °C eindringlich gewarnt hatten. Das Management von Thiokol überstimmte jedoch schließlich seine Ingenieure und gab seinem wichtigsten Kunden NASA offiziell die Startfreigabe. Wenige Sekunden nach dem Start versagte tatsächlich ein Dichtungs-O-Ring der rechten Feststoffrakete, und durch das entstandene Leck trat heißes Verbrennungsgas an einer Seite des Boosters aus. Die Flamme traf auf den Außentank und die Befestigung der Feststoffrakete, wodurch die Tankhülle zerstört wurde. Der Tank explodierte 73 Sekunden nach dem Start in 15 Kilometern Höhe, worauf das Shuttle durch die enormen aerodynamischen Kräfte zerstört wurde. Die sieben Astronauten überlebten das wahrscheinlich, starben aber spätestens beim Aufschlagen der Cockpitsektion auf die Wasseroberfläche des Atlantiks.`;
